### ISSUE TITLE
No longer builds

### ISSUE THREAD

**Issue by eayus** [cuddlefishie/toml-idr#1]
It seems that the parsing API in `contrib` has been changed, and it means the project no longer compiles.

**Comment by hydrolarus** [comment]
Hey! Thanks for the report! I'll look into making it compile on latest master, or is there a specific version you need to have supported? Things are moving quite fast and I'm pretty busy these days, so I'd rather update what's useful :sweat_smile:

**Comment by eayus** [comment]
If you could get it working on the latest master, that would be perfect!

**Comment by hydrolarus** [comment]
Okay, it should build on `master` now as of a1efaa7b79c2674e12b30f564703b04ee7d99e3f (at least with the build I had locally, `0.5.1-6f3ef813b`, testing *actually* latest master now)

Let me know if it works for you now!

**Comment by eayus** [comment]
Yep this builds for me now, nice job on sotring it so quickly!
